// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Optional field for partners who want customers to choose a user mapping to their system</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomerConfig_fields_field_type
    {
        [EnumMember(Value = "identity_mapping")]
        #pragma warning disable CS1591
        Identity_mapping,
        #pragma warning restore CS1591
    }
}
