// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomerConfig_fields : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Field name for customer input</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldDisplayName { get; set; }
#nullable restore
#else
        public string FieldDisplayName { get; set; }
#endif
        /// <summary>ID for customer input</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldId { get; set; }
#nullable restore
#else
        public string FieldId { get; set; }
#endif
        /// <summary>Optional field for partners who want customers to choose a user mapping to their system</summary>
        public global::ApiSdk.Models.CustomerConfig_fields_field_type? FieldType { get; set; }
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.CustomerConfig_fields_value? Value { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.CustomerConfig_fields_value Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.CustomerConfig_fields"/> and sets the default values.
        /// </summary>
        public CustomerConfig_fields()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.CustomerConfig_fields"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.CustomerConfig_fields CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.CustomerConfig_fields();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "field_display_name", n => { FieldDisplayName = n.GetStringValue(); } },
                { "field_id", n => { FieldId = n.GetStringValue(); } },
                { "field_type", n => { FieldType = n.GetEnumValue<global::ApiSdk.Models.CustomerConfig_fields_field_type>(); } },
                { "value", n => { Value = n.GetObjectValue<global::ApiSdk.Models.CustomerConfig_fields_value>(global::ApiSdk.Models.CustomerConfig_fields_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("field_display_name", FieldDisplayName);
            writer.WriteStringValue("field_id", FieldId);
            writer.WriteEnumValue<global::ApiSdk.Models.CustomerConfig_fields_field_type>("field_type", FieldType);
            writer.WriteObjectValue<global::ApiSdk.Models.CustomerConfig_fields_value>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
