// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SegmentDeltaSync : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The add property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.SegmentDeltaSync_add>? Add { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.SegmentDeltaSync_add> Add { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The remove property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.SegmentDeltaSync_remove>? Remove { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.SegmentDeltaSync_remove> Remove { get; set; }
#endif
        /// <summary>The segment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.SegmentInfo? Segment { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.SegmentInfo Segment { get; set; }
#endif
        /// <summary>The sync_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.SyncInfo? SyncInfo { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.SyncInfo SyncInfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.SegmentDeltaSync"/> and sets the default values.
        /// </summary>
        public SegmentDeltaSync()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.SegmentDeltaSync"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.SegmentDeltaSync CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.SegmentDeltaSync();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add", n => { Add = n.GetCollectionOfObjectValues<global::ApiSdk.Models.SegmentDeltaSync_add>(global::ApiSdk.Models.SegmentDeltaSync_add.CreateFromDiscriminatorValue)?.AsList(); } },
                { "remove", n => { Remove = n.GetCollectionOfObjectValues<global::ApiSdk.Models.SegmentDeltaSync_remove>(global::ApiSdk.Models.SegmentDeltaSync_remove.CreateFromDiscriminatorValue)?.AsList(); } },
                { "segment", n => { Segment = n.GetObjectValue<global::ApiSdk.Models.SegmentInfo>(global::ApiSdk.Models.SegmentInfo.CreateFromDiscriminatorValue); } },
                { "sync_info", n => { SyncInfo = n.GetObjectValue<global::ApiSdk.Models.SyncInfo>(global::ApiSdk.Models.SyncInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.SegmentDeltaSync_add>("add", Add);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.SegmentDeltaSync_remove>("remove", Remove);
            writer.WriteObjectValue<global::ApiSdk.Models.SegmentInfo>("segment", Segment);
            writer.WriteObjectValue<global::ApiSdk.Models.SyncInfo>("sync_info", SyncInfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
