// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebhookSyncRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Webhook action type</summary>
        public global::ApiSdk.Models.WebhookSyncRequest_action_type? ActionType { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Existing customer config if any (this will be empty for now)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.CustomerConfig? CustomerConfig { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.CustomerConfig CustomerConfig { get; set; }
#endif
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.SegmentDeltaSync? Data { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.SegmentDeltaSync Data { get; set; }
#endif
        /// <summary>The identifier for customer</summary>
        public Guid? IdToken { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.WebhookSyncRequest"/> and sets the default values.
        /// </summary>
        public WebhookSyncRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.WebhookSyncRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.WebhookSyncRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.WebhookSyncRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action_type", n => { ActionType = n.GetEnumValue<global::ApiSdk.Models.WebhookSyncRequest_action_type>(); } },
                { "customer_config", n => { CustomerConfig = n.GetObjectValue<global::ApiSdk.Models.CustomerConfig>(global::ApiSdk.Models.CustomerConfig.CreateFromDiscriminatorValue); } },
                { "data", n => { Data = n.GetObjectValue<global::ApiSdk.Models.SegmentDeltaSync>(global::ApiSdk.Models.SegmentDeltaSync.CreateFromDiscriminatorValue); } },
                { "id_token", n => { IdToken = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::ApiSdk.Models.WebhookSyncRequest_action_type>("action_type", ActionType);
            writer.WriteObjectValue<global::ApiSdk.Models.CustomerConfig>("customer_config", CustomerConfig);
            writer.WriteObjectValue<global::ApiSdk.Models.SegmentDeltaSync>("data", Data);
            writer.WriteGuidValue("id_token", IdToken);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
