// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Webhook action type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WebhookSyncRequest_action_type
    {
        [EnumMember(Value = "segment.users.sync")]
        #pragma warning disable CS1591
        SegmentUsersSync,
        #pragma warning restore CS1591
    }
}
